This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./dissertion.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file dissertion.acn....done (363 entries accepted, 0 rejected).
Sorting entries......done (3437 comparisons).
Generating output file dissertion.acr....done (132 lines written, 0 warnings).
Output written in dissertion.acr.
Transcript written in dissertion.alg.
