This is makeindex, version 2.15 [TeX Live 2021] (kpathsea + Thai support).
Scanning style file ./dissertion.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file dissertion.acn....done (410 entries accepted, 0 rejected).
Sorting entries......done (4225 comparisons).
Generating output file dissertion.acr....done (139 lines written, 0 warnings).
Output written in dissertion.acr.
Transcript written in dissertion.alg.
